export const FETCH_CONFIG = 'FETCH_CONFIG';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_PODCASTS = 'FETCH_PODCASTS';
export const FETCH_SEARCH_TERM = 'FETCH_SEARCH_TERM';
export const FETCH_PODCAST_INFO = 'FETCH_PODCAST_INFO';
